### ISSUE TITLE
ampliCan fails on an internmal exception

### ISSUE THREAD

**Issue by iamit87** [valenlab/amplican#10]
Hi,

I got the same error for about ~50% of my experiments:

Checking write access...
Checking configuration file...
Making alignments...
Aligning reads for mock
Aligning reads for tx
Saving alignments...
Saving parameters...
Saving unassigned sequences...
Saving barcode statistics...
Translating alignments into events...
Saving complete events - unfiltered...
Error: missing value where TRUE/FALSE needed
Traceback:

1. amplicanPipeline(config, fastq_folder, results_folder, knit_reports = FALSE)
2. aln_id[findLQR(aln_id), ]
3. `[.data.table`(aln_id, findLQR(aln_id), )
4. tryCatch(eval(.massagei(isub), x, ienv), error = function(e) .checkTypos(e, 
 .     names_x))
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)
8. .checkTypos(e, names_x)
9. stop(err$message, call. = FALSE)

The same config file on different experiments runs without any errors or exceptions.
I ran amplican 1.8.0 with default parameters:
"amplicanPipeline(config, fastq_folder, results_folder, knit_reports = FALSE)"

I attached my config input.
My FASTQ files are ~500 MB.  
But, I can send them if it's necessary. 
[config_csv.zip](https://github.com/valenlab/amplican/files/3930792/config_csv.zip)

Thanks!
Ido

**Comment by JokingHero** [comment]
This looks like some peculiar error with detection of off-target reads. If you can please send me somehow your fastq files, I will debug to the solution, I have no clue what can go wrong there.

**Comment by iamit87** [comment]
Hi,

Files are ~150MB. I sent you a google drive link. 
In the directory you will find all 4 FASTQ files (Treatment R1 & R2, Mock R1 & R2) and the config file.

**Comment by JokingHero** [comment]
In two days, when Bioconductor will rebuild the package, version 1.8.2 will have this fixed. Meanwhile, here is your config_summary file for these experiments.

[config_summary.zip](https://github.com/valenlab/amplican/files/3945061/config_summary.zip)

**Comment by JokingHero** [comment]
Thank you for providing the files, so that I could debug the error.

**Comment by iamit87** [comment]
Thanks!!!
