### ISSUE TITLE
'clusterCrit' library dependency no longer on CRAN

### ISSUE THREAD

**Issue by justinmrMIT** [valenlab/amplican#16]
It seems like one of the library dependencies of amplican 'clusterCrit' has been removed from CRAN as of 23-03-11: https://cran.r-project.org/web/packages/clusterCrit/index.html

Could you please fix this bug?

**Comment by JokingHero** [comment]
In the current Bioconductor it is fixed: https://www.bioconductor.org/packages/release/bioc/html/amplican.html
