### ISSUE TITLE
Directory pathing issues

### ISSUE THREAD

**Issue by chrispchen** [valenlab/amplican#18]
Hi, I'm trying to get AmpliCan working and I'm having some difficulties. I'm using Windows 10. 

**Here is my code that I've run:**

`# path to example config file
config <- "C:/Users/chris/Desktop/path/TrialConfig.csv"
# path to example fastq files
fastq_folder <- "C:/Users/chris/Desktop/path/"
# output folder, a full path
results_folder <- "C:/Users/chris/Desktop/path/TrialOut/"

#  run amplican
amplicanPipeline(config, fastq_folder, results_folder, fastqfiles = 1)

# results of the analysis can be found at
message(results_folder)`

**And this is the result of the code:**

`Checking write access...
Checking configuration file...
Making alignments...
Aligning reads for barcode_1
Aligning reads for barcode_2
Saving alignments...
Saving parameters...
Saving unassigned sequences...
Saving barcode statistics...
Translating alignments into events...
Saving complete events - unfiltered...
Shifting events as relative...
Saving shifted events - filtered...
Normalizing events...
Warning: Column 'Control' has no TRUE/1 values. Nothing to normalize.Saving normalized events...
Making reports... 
Due to high quality figures, it is time consuming. Use .Rmd templates for more control.

processing file: index.Rmd
  |........................                                                                            |  24% [unnamed-chunk-4] 
Quitting from lines 50-75 [unnamed-chunk-4] (index.Rmd)
Error in `data.table::fread()`:
! File 'C:UserschrisDesktoppathTrialOut/barcode_reads_filters.csv' does not exist or is non-readable. getwd()=='C:/Users/chris/Desktop/path/TrialOut/reports'
Backtrace:
 1. base::data.frame(data.table::fread(params$barcode_summary))
 2. data.table::fread(params$barcode_summary)`

What would you recommend that I do to resolve this? It looks like the path that index.Rmd is trying to use no longer contains slashes ?

**Comment by JokingHero** [comment]
Thanks for reporting this issue, I will think on a fix for this in the future version.

For now though you can simply fix those paths in the .Rmd files and then click on "knit" button in Rstudio. That will make the report for you.

**Comment by chrispchen** [comment]
Thank you for your prompt response!
