### ISSUE TITLE
Question: What is Unique reads?

### ISSUE THREAD

**Issue by AkaseKosuke** [valenlab/amplican#3]
Hello.
I am using ampliCan with 450 bp reference sequence and 2 x 300 bp data set. Unique reads decreased to about 70% compared with Good reads. Even when compared with the result from CrispRVariants, the read number is about 70%.
So I have a question about Unique reads.
What is Unique read? Also, what kind of operation is being performed specifically when calculating Unique reads?
Thank you.

**Comment by JokingHero** [comment]
Unique read is simply unique(forward read + reverse read). This is just very simple metric of heterogeneity of your reads and essential step in ampliCan. ampliCan uses this small optimization to collapse forward and reverse reads into unique pairs to reduce number of reads it needs to align.

If you have very little unique reads it means all reads are similar to each other. Possibly CRISPR did not cut, or have cut in very specific fashion all the time eg. at 1bp deletion in the same place in all edits. If you have very high number of unique reads, your reads are somewhat different from each other (sequencing errors and CRISPR activity contribute to that). Both of those cases can happen in successful experiments. 

If you want you can email me (kornel.labun at gmail) your ampliCan reports and I can interpret these for you. Just FYI if you have such long amplicon sequences you can right click each of the images in the report and open in new window to zoom on them.
