### ISSUE TITLE
multiple guides within the same sample per amplicon

### ISSUE THREAD

**Issue by borauyar** [valenlab/amplican#4]
Does `amplican` support the condition when you have multiple guides designed for the same amplicon? In the sample configuration file [here](http://bioconductor.org/packages/release/bioc/vignettes/amplican/inst/doc/amplicanOverview.html#configuration-file), there is always one guide RNA per sample. Is it possible to configure samples such that they may contain multiple guides?

**Comment by JokingHero** [comment]
Only column "ID" has to be unique which is just indicating naming, in the example you linked I see two guides per fastq files (R1_001.fastq + R2_001.fastq). The primers from columns "Forward_Primer" and "Reverse_Primer" are used to split the reads to their respective "Amplicon" column and align.

For each fastq file you can specify any number of guides, just make sure combinations of forward and reverse primers are unique for each guide in respective fastq file. "Barcode" column is a "nice" name for the sample.

If you used the same primers for multiple guides in the sample, that means we can not detect which reads belong to which amplicon. In that case use aligner like bwa to get alignments.  BAM files from bwa alignments can be read by ampliCan, but not in the standardized pipeline. You can still achieve the same as in `amplicanPipeline` is you use `cigarsToEvents` from the current bioconductor devel version of amplican to load the events and then you can process them following similar steps as in `amplicanPipeline`.

**Comment by borauyar** [comment]
Thank you!
