### ISSUE TITLE
folder_name_format

### ISSUE THREAD

**Issue by AndreaBarghetti** [valenlab/amplican#6]
Hi
I tried Amplican and worked all very well

In my first attempt however I used amplicanPipeline() inputing folders path with an end dash:

amplicanPipeline("config_file", "fastq/", "results/")

This generate errors when knitting the reports (it will try to find files into "results//...")

I don't know if is it worth specifying it somewhere ("don´t add "/" !!!)

thanks for a nice tool!

**Comment by JokingHero** [comment]
This should be fixed now, soon bioc devel will update, and not long after that bioc 3.9 will release and it will be fixed there.
