### ISSUE TITLE
Final edit rates plot/table

### ISSUE THREAD

**Issue by iamit87** [valenlab/amplican#9]
Hi,

I ran Amplican on a multiplexed experiment with 1 on-target site and 49 off-targets sites.
The treatment experiment also has a matching control experiment.
I'm interested in the final normalized editing activity for each site. 

**A few questions:**
1. I've noticed that "config_summary.csv" doesn't have the final normalized edit rates. Does the final rate only exist in the RMD/HTML reports? I need to run many experiments, so manually eye bowling many plots is not an option for me. 
2. The normalized score plot ("Variants") has a "resolution" of 1%. Meaning, for off-target sites with activity lower than <1% the reported editing rate is 0%. Where can I find the exact editing activity number? 
3. Is there a way to exclude mismatches from my final report? Mismatches are extremely noisy, and even with normalization, they can badly influence the final editing activity.

Many thanks!

**Comment by JokingHero** [comment]
Hi,

1. Final editing rates are not present in the "config_summary.csv", but they can be calculated easily from the column `Reads_Edited` - number of edited reads, where edited means a read had deletion or insertion or is marked as HDR. Divide by column `Reads_Filtered` - number of all reads after filtering. This is explained in the main vignette, maybe its not that clear though.

Those are normalized values, by default normalization assumes same "Guide" + "Group", make sure these are same for your off-targets as the target guide, read more about it in `amplicanNormalize`.

2. Variant plot is just for visualization, there is no real value there in including everything below 1% in the plot. If you want to achieve really high precision in the estimating off-target activity you can lower parameter `min_freq` of the `amplicanPipeline` function.

3. Mismatches are not counted in ampliCan as editing int he summary_config file however there are information on the plots on them, to keep tabs on what is going on.

**Comment by iamit87** [comment]
Hi,

Thanks for the quick response!

Regarding 1 - 
I used the same "Guide" + "Group". 
I ran ampliCan twice:
1. Tx only setup. 
2. Tx+Control setup. 
In both config_summary.csv reports - The number of reads_edited in my Tx sites were identical. 
Meaning, the normalization had no effect. 
But, the reported editing activity in ampliCan final report (amplican_report.Rmd) was changed. Dramatically for some sites. Is there a chance that the edited_reads column is before normalization? 
I can send my running parameters if necessary.  

Regarding 2 - If I understand correctly - lowering min_freq can cause the removal of real editing activity - correct? 

Thanks again!
Ido.

**Comment by JokingHero** [comment]
To clarify, reads_edited is definitely including normalized counts. There is no amplican_report.Rmd, there is however amplicon_report.Rmd which is a summary of "per amplicon" results. Send me please, your config file, I can take a look whether you specified controls correctly.

Regarding 2. lowering min_freq can remove real editing activity - true, I think its best to visually define what is correct min_freq level for your experiment on the mismatch_plot, where general level of mismatches would define the "min_freq".

**Comment by iamit87** [comment]
Thanks!

I ran another experiment with 35 sites.
Unlike the previous experiment - This time one site had different results when adding the mock.
Makes sense? 

I attached two config_summary files.
one - Treatment and mock setup.
second - Only treatment.

Can you please check that I specified controls correctly?
Thanks again,
Ido.

[config_summary.zip](https://github.com/valenlab/amplican/files/3922236/config_summary.zip)

**Comment by JokingHero** [comment]
I checked your configs, seems to me everything is in order. Sometimes it also happens that even with controls editing rates will not be changed for "treated" sites, its because ampliCan is working on the event level, not read level, its more precise. For instance a deletion of 5bp at pos -10 from the edit site that occurs in the control will not be removed from the treated sample as its not there at all.
And even sometimes events from the control will be removed from the treatment, yet the general editing rate won't be influenced because some reads had multiple editing events, one from the background noise - removed thanks to control, and some from real editing.

**Comment by iamit87** [comment]
Thanks!
